ALTER TABLE [dbo].[UploadBatch]
    ADD CONSTRAINT [PK_Batch] PRIMARY KEY CLUSTERED ([BatchId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

