ALTER TABLE [dbo].[MediaQueue]
    ADD CONSTRAINT [PK_MediaQueue] PRIMARY KEY CLUSTERED ([MediaQueueId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

