ALTER TABLE [dbo].[MediaFile]
    ADD CONSTRAINT [PK_PhotoFile] PRIMARY KEY CLUSTERED ([MediaId] ASC, [FileId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

