ALTER TABLE [dbo].[Exif]
    ADD CONSTRAINT [PK_Exif_1] PRIMARY KEY CLUSTERED ([MediaId] ASC, [Key] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

