ALTER TABLE [dbo].[MediaLedger]
    ADD CONSTRAINT [PK_MediaLedger] PRIMARY KEY CLUSTERED ([MediaLedgerId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

