ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [Dev.Momntz], FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Dev.Momntz.mdf', SIZE = 2048 KB, FILEGROWTH = 1024 KB) TO FILEGROUP [PRIMARY];

